#!/usr/bin/env bash

source-dist(){
    python setup.py sdist
}

pip-source(){
    pip install ./dist/mergefast-1.1.2.tar.gz
}

trace(){
    sudo dtrace -c "python tests/perf.py" -o out.stacks -n 'profile-997 /pid == $target/ { @[ustack(100)] = count(); }'
}

flamegraph(){
    cat out.stacks | /Users/adam/sandbox/FlameGraph/stackcollapse.pl | /Users/adam/sandbox/FlameGraph/flamegraph.pl > flamegraph.svg
}
