VERSION 0.7

# Todo:
# - +publish uses staging pypi
# - twine upload steps
# - poetry upload steps

clean:
   LOCALLY
    RUN rm -rf build dist *.egg-info 
    RUN rm ./mergeslow/*.so || true

deps:
    FROM python:3.11-buster
    RUN pip install poetry

build:
    FROM +deps
    WORKDIR /code
    COPY --dir mergeslow tests .
    COPY setup.py poetry.lock pyproject.toml README.md  .

    # Two ways to build
    # creates a sdist for pypi
    RUN python3 setup.py sdist

    # create bdist for pypy, in theory
    # this is not useful, because need to use a manylinux image to make a wheel that works on pypi
    RUN python setup.py bdist_wheel

    SAVE ARTIFACT ./dist AS LOCAL .

test-direct:
    FROM +build
    RUN poetry install
    RUN poetry run python tests/test.py 

test-dist-install:
    FROM python:3.11-buster
    COPY +build/dist dist
    ENV TARFILE=$(ls ./dist/*.tar.gz)
    RUN pip install "$TARFILE"
    COPY tests .
    RUN python test.py

publish:
    FROM +build
    RUN poetry publish --repository testpypi -n

test-pypi-install:
    FROM python:3.11-buster
    RUN pip install "mergeslow"
    COPY tests .
    RUN python test.py
