VERSION 0.7

clean:
   LOCALLY
    RUN rm -rf build dist *.egg-info 

deps:
    FROM python:3.11-buster
    RUN pip install poetry twine

build:
    FROM +deps
    WORKDIR /code
    COPY --dir mergeslow tests .
    COPY setup.py poetry.lock pyproject.toml README.md .
    # Two ways to build
    # creates a sdist for pypi
    RUN python3 setup.py sdist

    # create bdist for pypy
    RUN python setup.py bdist_wheel
    SAVE ARTIFACT ./dist AS LOCAL .

twine-publish:
    FROM +build
    COPY +build/dist dist
    RUN twine upload --repository-url https://upload.pypi.org/legacy/ dist/*

poetry-publish:
    FROM +build
    RUN poetry config repositories.testpypi https://test.pypi.org/legacy/
    RUN poetry publish --build --repository testpypi -n

test-direct:
    FROM +build
    RUN poetry install
    RUN poetry run python tests/test.py 

test-dist-tar-install:
    FROM python:3.11-buster
    COPY +build/dist dist
    ENV TARFILE=$(ls ./dist/*.tar.gz)
    RUN pip install "$TARFILE"
    COPY tests .
    RUN python test.py

test-dist-whl-install:
    FROM python:3.11-buster
    COPY +build/dist dist
    ENV WHLFILE=$(ls ./dist/*.whl)
    RUN pip install "$WHLFILE"
    COPY tests .
    RUN python test.py

test-pypi-install:
    FROM python:3.11-buster
    RUN pip install --index-url https://test.pypi.org/simple/ "mergeslow"
    COPY tests .
    RUN python test.py
